### ISSUE TITLE
Document numpydoc style for Returns sections

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#90] opened 2023-04-11 17:15 UTC
With this `Returns` section of a docstring (https://github.com/rstudio/py-shiny/blob/d036a8aa/shiny/reactive/_poll.py#L257-L263):

```
    Returns
    -------
    A decorator that should be applied to a no-argument function that (expensively)
    reads whatever data is desired. (This function may be a regular function or a
    coroutine function.) The result of the decorator is a reactive ~shiny.reactive.Calc
    that always returns up-to-date data, and invalidates callers when changes are
    detected via polling.
```

It is rendered in a table with columns named Type and Description, but it is not information that makes sense in a table.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/86978/231239050-0fb8068d-dcf2-4c3d-9d0c-05019cd610b2.png">

**Comment by machow** [comment] 2023-04-13 20:06
This looks like a duplicate of

* https://github.com/machow/quartodoc/issues/96

Do you mind weighing in there on numpydoc style for returns? I'm curious if sphinx handles a returns section like above

**Comment by wch** [comment] 2023-04-13 20:47
Note that #96 is not exactly the same. That issue is about text in backticks disappearing.

**Comment by machow** [comment] 2023-04-13 20:49
Why do you want backticks in the type column? I don't think there is a way to have a valid type annotation with backticks

**Comment by machow** [comment] 2023-04-14 17:52
See #96, your examples in both issues do not conform to numpydoc format. If you want to change the format, either open an issue on numpydoc or griffe. I'll label this issue, to make sure I add examples of numpydoc sections, and notes about gotchas like this one.

**Comment by machow** [comment] 2023-04-14 18:00
I've opened a new issue https://github.com/machow/quartodoc/issues/108 to try and capture the request that a single return result gets documented differently.

**Comment by machow** [comment] 2023-05-02 21:32
I've added a note that we use numpydoc style (with links to numpydoc), and a note on this example

https://machow.github.io/quartodoc/get-started/docstring-examples.html#returns-using-type-annotation


![Image](https://user-images.githubusercontent.com/2574498/235790856-c1c2624f-7834-4f61-9d7c-50ef8e3eb662.png)

**Closed by machow** 2023-05-02 21:32 UTC
Labels: type:documentation, shiny
